-- Top 10 rows of dataset
SELECT * FROM customer_purchase_behavior LIMIT 10;
-----------------------------------------------------------------------------------------------------------------------------------------
--Q1: What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer_purchase_behavior
GROUP BY gender;
-----------------------------------------------------------------------------------------------------------------------------------------
--Q2: Which customers used a discount but still spent more than average purchase amount?
SELECT customer_id, purchase_amount
FROM customer_purchase_behavior
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_purchase_behavior);
-----------------------------------------------------------------------------------------------------------------------------------------
--Q3: Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric), 2) AS "Average Product Rating"
FROM customer_purchase_behavior
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;
-----------------------------------------------------------------------------------------------------------------------------------------
--Q4: Compare the average purchase amount between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS "Average Purchase Amount"
FROM customer_purchase_behavior
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type;
-----------------------------------------------------------------------------------------------------------------------------------------
--Q5: Do subscribed customers spend more? Compare average spend and total revenue between subcribers and non-subscribers.
SELECT subscription_status AS "Subscription",
COUNT(customer_id) AS "Total Customers",
ROUND(AVG(purchase_amount), 2) AS "Average Spend",
SUM(purchase_amount) AS "Total Revenue"
FROM customer_purchase_behavior
GROUP BY subscription_status
ORDER BY "Total Revenue" DESC;
-----------------------------------------------------------------------------------------------------------------------------------------
--Q6: Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased AS "Products",
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) as "Discount Rate"
FROM customer_purchase_behavior
GROUP BY item_purchased
ORDER BY "Discount Rate" DESC
LIMIT 5;
-----------------------------------------------------------------------------------------------------------------------------------------
--Q7: Segment customers into New, Returning, and Loyal based on their total number of previous purchases, show the count of each segment.
WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer_purchase_behavior
)

SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment
ORDER BY "Number of Customers" DESC;
-----------------------------------------------------------------------------------------------------------------------------------------
--Q8: What are the top 3 most purchased products within each category?
WITH item_count AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer_purchase_behavior
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <= 3;
-----------------------------------------------------------------------------------------------------------------------------------------
--Q9: Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status AS "Subscription Status",
COUNT(customer_id) AS "Repeat Buyers"
FROM customer_purchase_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;
-----------------------------------------------------------------------------------------------------------------------------------------
--Q10: What is the revenue contribution to each age group?
SELECT age_group,
SUM(purchase_amount) AS "Total Revenue"
FROM customer_purchase_behavior
GROUP BY age_group
ORDER BY "Total Revenue" DESC;